name: Bug Report
description: Report a bug or issue with Radar
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots
      placeholder: Paste screenshots here...

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: "e.g., Chrome 120, Safari 17"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: "e.g., macOS 14, Windows 11"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the problem
      placeholder: Add any other context...
